---
- name: Ansible Find
  hosts: localhost
  vars:
    path_to_logs: /var/log
    pattern_to_find_logs: '*.log'
    age_of_find: 30d
  tasks:
   - name : Find files older than 30 days
     become: yes
     find:
       paths: "{{path_to_logs}}"
       patterns: "{{pattern_to_find_logs}}"
       age: "{{age_of_find}}"
       age_stamp: mtime
     register: output
   - debug:
        var: output

- name: Create directories for back_up
  hosts: backup_host
  vars:
    path_to_back_up: /back_up/var/log/
    first_directory_for_backup: /back_up
  tasks:
  - name: Mk dir
    file:
        path: "{{path_to_back_up}}"
        state: directory
        mode: '0755'
        recurse: yes
    
  - name: Copy the files to remote host
    copy:
      src: "{{item.path}}"
      dest: "{{first_directory_for_backup}}/{{item.path}}"
      owner: root
      mode: 600
    with_items: 
    - "{{ hostvars['localhost']['output'].files }}"
